mysql:
    image: mysql:5.5
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./mysql:/config
    environment:
        MYSQL_ROOT_PASSWORD : 123456
    command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
        - --skip-character-set-client-handshake
    ports:
        - "3016:3306"

main:
    image: nuts:php-7.0
    volumes:
        - ../data/storage:/var/www/saishi_storage
        - ../data/uploads:/var/www/saishi_public/uploads
        - .:/var/www/html
    ports:
        - "3013:80"
    links:
        - mysql




